#!/bin/bash

# Image Download Helper Script for DRNF Website
# Created: November 13, 2025
# Purpose: Create directory structure and provide download instructions

echo "=================================================="
echo "DRNF Website - Partner Image Download Helper"
echo "=================================================="
echo ""

# Create organized directory structure
echo "Creating organized image directories..."
mkdir -p images/loocafe
mkdir -p images/ixora
mkdir -p images/chai-counters
mkdir -p images/community
mkdir -p images/workers
mkdir -p images/stock-placeholders

echo "✓ Directories created successfully"
echo ""

# Display current image inventory
echo "Current image inventory:"
echo "------------------------"
ls -lh images/ | grep -E '\.jpg|\.png|\.jpeg' | awk '{print $9, "(" $5 ")"}'
echo ""
echo "Total images: $(ls images/*.{jpg,png,jpeg} 2>/dev/null | wc -l)"
echo ""

# Display instructions
echo "=================================================="
echo "STEP 1: Download Images from Partner Websites"
echo "=================================================="
echo ""
echo "Visit these websites and download high-quality images:"
echo ""
echo "1. LooCafe (https://loocafe.com)"
echo "   - Homepage hero images (facilities)"
echo "   - Toilet Tales blog (https://loocafe.com/toilettales)"
echo "   - Gallery/portfolio sections"
echo "   - Save to: images/loocafe/"
echo ""
echo "2. Ixora Group (https://ixoragroup.com)"
echo "   - CSR / Corporate Social Responsibility section"
echo "   - Team photos and worker images"
echo "   - Community service activities"
echo "   - Save to: images/ixora/"
echo ""
echo "3. News Articles"
echo "   - Telangana Today: https://telanganatoday.com/charitable-trust-launches-free-chai-counter-in-hyderabad"
echo "   - Search: 'Ixora PPE distribution Siasat Daily'"
echo "   - Save to: images/chai-counters/ or images/community/"
echo ""
echo "4. Stock Photos (if needed)"
echo "   - Unsplash: https://unsplash.com"
echo "   - Pexels: https://pexels.com"
echo "   - Search terms in IMAGE_SOURCING_GUIDE.md"
echo "   - Save to: images/stock-placeholders/"
echo ""

echo "=================================================="
echo "STEP 2: Optimize Downloaded Images"
echo "=================================================="
echo ""
echo "After downloading, optimize images using one of these methods:"
echo ""
echo "Method 1: Online Tools (Easy)"
echo "  - TinyPNG: https://tinypng.com"
echo "  - Squoosh: https://squoosh.app"
echo "  - Target: <200KB per image, 85% quality"
echo ""
echo "Method 2: ImageMagick (Command line)"
echo "  - Install: sudo apt install imagemagick (Linux)"
echo "  - Install: brew install imagemagick (Mac)"
echo "  - Run: mogrify -quality 85 -resize 1920x images/**/*.jpg"
echo ""

echo "=================================================="
echo "STEP 3: Update HTML Files"
echo "=================================================="
echo ""
echo "Update these files with new image paths:"
echo "  - index.html (hero, initiatives section)"
echo "  - loocafe-impact.html (hero, facility images)"
echo "  - frontline-workers.html (worker images, PPE)"
echo "  - chai-counters.html (counter operations)"
echo ""
echo "See IMAGE_SOURCING_GUIDE.md Section 7 for examples"
echo ""

echo "=================================================="
echo "STEP 4: Test and Deploy"
echo "=================================================="
echo ""
echo "1. Test locally:"
echo "   python -m http.server 8000"
echo "   Visit: http://localhost:8000"
echo ""
echo "2. Verify all images load correctly"
echo ""
echo "3. Run Lighthouse audit (Chrome DevTools)"
echo ""
echo "4. Commit and push:"
echo "   git add images/"
echo "   git commit -m 'Add partner images from LooCafe and Ixora'"
echo "   git push origin claude/issue-2-20251113-0937"
echo ""

echo "=================================================="
echo "Priority Images to Download First"
echo "=================================================="
echo ""
echo "HIGH PRIORITY (Do these first):"
echo "  1. LooCafe facility hero (loocafe.com homepage)"
echo "  2. Chai counter in action (Telangana Today article)"
echo "  3. Frontline workers (ixoragroup.com CSR section)"
echo "  4. PPE distribution event (Siasat Daily or Ixora)"
echo "  5. LooCafe location with chai counter"
echo ""
echo "See IMAGE_SOURCING_GUIDE.md for complete list of 24 images"
echo ""

echo "=================================================="
echo "Need Help?"
echo "=================================================="
echo ""
echo "Detailed instructions: IMAGE_SOURCING_GUIDE.md"
echo "Asset list: ASSET_NEEDS_LIST.md"
echo "Contact: info@drnf.org or +91 9966906781"
echo ""
echo "Ready to download images!"
echo "=================================================="
